version: '3.8'

services:
    php:
        container_name: calculator-refactor-master-php
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - .:/var/www/html